### ISSUE TITLE
Chewies Bowcaster autoloots

### ISSUE THREAD

**Issue by awikGgb** [rotjmud/issues#11]
1642(2084)hitp 856(856)forcep 273(273)move> You shout, 'What's that over there?!?'
Chewbacca turns around to see what all the fuss is about.
Chewbacca makes a strange sound but is suddenly very silent as you place Thamael's Blade Of
Assassination in his back. (**1642**)
Chewbacca is dead!  R.I.P.
You receive your share of experience -- 2962959 points.
You are awarded 1 skill point for your outstanding performance.
emote grin evilly and puts a SP to the pile
Your blood freezes as you hear Chewbacca's death cry.
You get a pile of credits from the corpse of Chewbacca.
There were 975 credits.
You split 975 credits among 1 members --  975 credits each.
You get a large bandolier from the corpse of Chewbacca.
You get a frag grenade from the corpse of Chewbacca.
Object personalized.
You get Chewbacca's Bowcaster from the corpse of Chewbacca.

**Comment by coveguyz01** [comment]
fixed
