### ISSUE TITLE
Apoc mask have wrong bind

### ISSUE THREAD

**Issue by awikGgb** [rotjmud/issues#14]
ident mask
You feel informed:
Object 'an Apocalyptic Mask', Item type: Armor
It can be worn: Inventory Head 
Item is: Unmaskable !Locate Upgradeable UNIQUE LEGENDARY 
Weight: 6, Value: 100000, Rent: 10000
AC-apply is 8
Quality: Brand New.
Special: Increases castable force damage by 10%.
Can affect you as :
   Affects: All Stats by 8
   Affects: Evil Alignment by 10

**Comment by coveguyz01** [comment]
Fixed

**Comment by awikGgb** [comment]
Actually, the rest of cube loot don't bind on pickup, they bind on use. Now mask binds on pickup. Since it is not 120 gear perhaps on wear is enough?

![image](https://user-images.githubusercontent.com/51785694/102515138-a81d7000-408d-11eb-932f-42beb5e362ac.png)

**Comment by fourty7** [comment]
Cube gear is good enough that it warrants being bind on pickup.
