### ISSUE TITLE
Backstab on targets with force field

### ISSUE THREAD

**Issue by awikGgb** [rotjmud/issues#6]
Backstab opener on a target with force field(Darktroopers and termination droid for example). 
You can get a crit message on the attack, you can get a message field breaks from the crit, but message that the backstab miss. Also Darktrooper put up bubble again in combat during the backstab lag

**Comment by coveguyz01** [comment]
Added a lag to mobs recasting force field.

You miss backstab because the force field absorbs it. Which I believe causes you to also miss a doublebackstab.
